import { FaHandHoldingUsd, FaLightbulb, FaUserPlus, FaCog } from "react-icons/fa";
import { REVENUE_SPLIT } from "@/config/constants";

const RevenueSplit = () => {
  return (
    <div className="gradient-card rounded-xl p-6 border border-gray-800">
      <h3 className="text-xl font-medium text-white mb-6 flex items-center">
        <FaHandHoldingUsd className="text-primary mr-3" />
        Revenue Split
      </h3>
      
      <div className="bg-gray-800/80 p-6 rounded-lg mb-6">
        <div className="flex items-center justify-center mb-8">
          <div className="relative w-48 h-48">
            {/* Donut chart representing revenue split */}
            <svg viewBox="0 0 36 36" className="w-full h-full">
              {/* 60% Creator - Primary */}
              <path d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" fill="none" stroke="#5D2E8C" strokeWidth="3" strokeDasharray="60, 100" strokeLinecap="round" transform="rotate(90, 18, 18)"></path>
              {/* 10% Referral - Orange */}
              <path d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" fill="none" stroke="#FF8855" strokeWidth="3" strokeDasharray="10, 100" strokeDashoffset="-60" strokeLinecap="round" transform="rotate(90, 18, 18)"></path>
              {/* 30% Gagsty - Cyan */}
              <path d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" fill="none" stroke="#00E0FF" strokeWidth="3" strokeDasharray="30, 100" strokeDashoffset="-70" strokeLinecap="round" transform="rotate(90, 18, 18)"></path>
            </svg>
            <div className="absolute inset-0 flex items-center justify-center">
              <div className="text-center">
                <div className="text-sm text-gray-400">Total Split</div>
                <div className="text-xl font-bold text-white">100%</div>
              </div>
            </div>
          </div>
        </div>
        
        <div className="grid grid-cols-3 gap-4 text-center">
          <div>
            <div className="text-sm text-gray-400">Creator</div>
            <div className="text-xl font-bold text-primary">{REVENUE_SPLIT.creator}%</div>
          </div>
          <div>
            <div className="text-sm text-gray-400">Referral</div>
            <div className="text-xl font-bold text-[#FF8855]">{REVENUE_SPLIT.referral}%</div>
          </div>
          <div>
            <div className="text-sm text-gray-400">Gagsty</div>
            <div className="text-xl font-bold text-accent">{REVENUE_SPLIT.platform}%</div>
          </div>
        </div>
      </div>
      
      <div className="space-y-4">
        <div className="bg-primary/10 p-4 rounded-lg border border-primary/30">
          <h4 className="text-white font-medium mb-2 flex items-center">
            <FaLightbulb className="text-primary mr-2" />
            Game Creator
          </h4>
          <p className="text-sm text-gray-300">Earn {REVENUE_SPLIT.creator}% of all Chips generated by your game. Includes in-game purchases, ads, and referrals.</p>
        </div>
        
        <div className="bg-[#FF8855]/10 p-4 rounded-lg border border-[#FF8855]/30">
          <h4 className="text-white font-medium mb-2 flex items-center">
            <FaUserPlus className="text-[#FF8855] mr-2" />
            Referral Bonus
          </h4>
          <p className="text-sm text-gray-300">Earn {REVENUE_SPLIT.referral}% when you refer a user who creates or plays games. Lifetime reward on their activity.</p>
        </div>
        
        <div className="bg-accent/10 p-4 rounded-lg border border-accent/30">
          <h4 className="text-white font-medium mb-2 flex items-center">
            <FaCog className="text-accent mr-2" />
            Platform Fee
          </h4>
          <p className="text-sm text-gray-300">{REVENUE_SPLIT.platform}% goes to Gagsty to maintain and improve the platform, AI infrastructure, and community initiatives.</p>
        </div>
      </div>
    </div>
  );
};

export default RevenueSplit;
